from fpdf import FPDF
import io
import markdown

class PDF(FPDF):
    def __init__(self, doc_type="formal"):
        super().__init__()
        self.doc_type = doc_type
        
    def header(self):
        if self.page_no() == 1:
            return
            
        font_family = 'Times' if self.doc_type == 'academic' else 'Helvetica'
        self.set_font(font_family, 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, 'Generated by BriefPort', align='R')
        self.ln(10)

    def footer(self):
        if self.page_no() == 1:
            return
            
        self.set_y(-15)
        font_family = 'Times' if self.doc_type == 'academic' else 'Helvetica'
        self.set_font(font_family, 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

def sanitize_text(text: str) -> str:
    if not text:
        return ""

    replacements = {
        "\u2013": "-",    # en-dash
        "\u2014": "--",   # em-dash
        "\u2018": "'",    # left single quote
        "\u2019": "'",    # right single quote
        "\u201c": '"',    # left double quote
        "\u201d": '"',    # right double quote
        "\u2026": "...",  # ellipsis
        "\u2011": "-",    # non-breaking hyphen
        "\u00a0": " ",    # non-breaking space
        "\u2022": "*",    # bullet point
        "\uFF1F": "?",    # question mark
    }
    
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    
    return text.encode('latin-1', 'replace').decode('latin-1')

def create_title_page(pdf, title, doc_type):
    pdf.add_page()
    
    font_family = 'Times' if doc_type == 'academic' else 'Helvetica'
    title_color = (0, 0, 0) if doc_type == 'academic' else (0, 51, 102)
    
    pdf.ln(60)
    pdf.set_font(font_family, 'B', 24)
    pdf.set_text_color(*title_color)
    pdf.multi_cell(0, 10, title, align='C')
    
    pdf.ln(20)
    pdf.set_font(font_family, '', 12)
    pdf.set_text_color(100)
    pdf.cell(0, 10, f"Document Type: {doc_type.capitalize()}", align='C')
    pdf.ln(8)
    pdf.cell(0, 10, "Generated by BriefPort", align='C')
    pdf.ln(8)
    pdf.cell(0, 10, "Your AI Assistant", align='C')
    
    pdf.add_page()

def generate_pdf_bytes(title: str, content: str, doc_type: str = "formal") -> bytes:
    # 1. Sanitize Inputs
    clean_title = sanitize_text(title)
    clean_content = sanitize_text(content)

    pdf = PDF(doc_type=doc_type)
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # 2. Create the Title Page
    create_title_page(pdf, clean_title, doc_type)
    
    # 3. Configure Fonts for Content
    font_family = 'Times' if doc_type == 'academic' else 'Helvetica'
    pdf.set_font(font_family, '', 12)
    pdf.set_text_color(0) # Black text

    # 4. Convert Markdown to HTML
    html_content = markdown.markdown(clean_content)
    
    # 5. Inject Inline Styles for Justification and Line Height
    html_content = html_content.replace(
        "<p>", 
        '<p align="justify" style="line-height: 1.5;">'
    )
    
    # Apply to List Items: Justify and Double Line Height
    html_content = html_content.replace(
        "<li>", 
        '<li><p align="justify" style="line-height: 2.0;">'
    )
    html_content = html_content.replace(
        "</li>", 
        "</p></li>"
    )
    
    # 6. Write HTML to PDF
    styled_html = f"""
    <font face="{font_family}" size="12">
    {html_content}
    </font>
    """
    
    # Note: write_html handles the flow of text automatically
    pdf.write_html(styled_html)
    
    # 7. Output bytes
    pdf_buffer = io.BytesIO()
    pdf_bytes = pdf.output(dest='S')
    
    return bytes(pdf_bytes)